In [1]:
import pandas as pd
import numpy as np

# Games

In [8]:
games_data = pd.read_csv('nfl-big-data-bowl-2021/games.csv')

In [15]:
games_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 253 entries, 0 to 252
Data columns (total 6 columns):
gameId             253 non-null int64
gameDate           253 non-null object
gameTimeEastern    253 non-null object
homeTeamAbbr       253 non-null object
visitorTeamAbbr    253 non-null object
week               253 non-null int64
dtypes: int64(2), object(4)
memory usage: 12.0+ KB

In [28]:
games_data

         gameId    gameDate gameTimeEastern homeTeamAbbr visitorTeamAbbr  week
0    2018090600  09/06/2018        20:20:00          PHI             ATL     1
1    2018090901  09/09/2018        13:00:00          CLE             PIT     1
2    2018090902  09/09/2018        13:00:00          IND             CIN     1
3    2018090903  09/09/2018        13:00:00          MIA             TEN     1
4    2018090900  09/09/2018        13:00:00          BAL             BUF     1
..          ...         ...             ...          ...             ...   ...
248  2018123013  12/30/2018        16:25:00          DEN             LAC    17
249  2018123015  12/30/2018        16:25:00          SEA             ARI    17
250  2018123014  12/30/2018        16:25:00           LA              SF    17
251  2018122200  12/22/2018        16:30:00          TEN             WAS    16
252  2018122201  12/22/2018        20:20:00          LAC             BAL    16

[253 rows x 6 columns]

## Important features to look at in the data

- gameId: will likely be used on the weekly data to find what teams are playing.
- gameTimeEastern: could be an interesting stat to look at. maybe teams do better in earlier games than later one so it could be a stat thats used later on
- Home and away teams

# Players

In [32]:
players_data = pd.read_csv('nfl-big-data-bowl-2021/players.csv')

In [33]:
players_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 7 columns):
nflId          1303 non-null int64
height         1303 non-null object
weight         1303 non-null int64
birthDate      1303 non-null object
collegeName    1303 non-null object
position       1303 non-null object
displayName    1303 non-null object
dtypes: int64(2), object(5)
memory usage: 71.4+ KB

In [34]:
players_data

,nflId,height,weight,birthDate,collegeName,position,displayName
0,2539334,72,190,1990-09-10,Washington,CB,Desmond Trufant
1,2539653,70,186,1988-11-01,Southeastern Louisiana,CB,Robert Alford
2,2543850,69,186,1991-12-18,Purdue,SS,Ricardo Allen
3,2555162,73,227,1994-11-04,Louisiana State,MLB,Deion Jones
4,2555255,75,232,1993-07-01,Minnesota,OLB,De'Vondre Campbell
...,...,...,...,...,...,...,...
1298,2553798,6-2,235,09/17/1991,Vanderbilt,LS,Andrew East
1299,2556814,6-2,200,05/17/1994,Duke,WR,Max McCaffrey
1300,2552576,78,231,1992-04-25,Oregon State,QB,Sean Mannion
1301,2561469,69,187,1993-03-15,Alabama-Birmingham,CB,Darious Williams
1302,2558095,6-2,196,10/12/1995,LSU,WR,Malachi Dupre

In [38]:
players_data.position.unique()

array(['CB', 'SS', 'MLB', 'OLB', 'FS', 'WR', 'QB', 'TE', 'RB', 'DE', 'LB',
       'FB', 'ILB', 'DB', 'S', 'HB', 'NT', 'P', 'LS', 'K', 'DT'],
      dtype=object)

### Positions

CB - Corner Back;
SS - Strong Safety;
MLB - Middle Linebacker;
OLB - Outside Linebacker;
FS - Free Safety;
WR - Wide Receiver;
QB - Quarterback;
TE - Tight End;
RB - Running Back;
DE - Defensive End;
LB - Linebacker;
FB - Fullback;
ILB - Inside Linebacker;
DB - Defensive Back;
S - Safety;
HB - Halfback;
NT - Nose Tackle;
P - Punter;
LS - Left Safety;
K - Kicker;
DT - Defensive Tackle

## Important features to look at in the data

- nflid - similarly to game id it could be used to identify the play on specific plays
- height and weight - see if player size at specific position helps when it comes to generating passing plays
- position
- college seems fairly irrelevant when it comes to performance. Generally the school a player goes to doesnt mean as much as where they got drafted but since we dont have that stat maybe it will be useful alter on

# Plays

In [35]:
plays_data = pd.read_csv('nfl-big-data-bowl-2021/plays.csv')

In [36]:
plays_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19239 entries, 0 to 19238
Data columns (total 27 columns):
gameId                    19239 non-null int64
playId                    19239 non-null int64
playDescription           19239 non-null object
quarter                   19239 non-null int64
down                      19239 non-null int64
yardsToGo                 19239 non-null int64
possessionTeam            19239 non-null object
playType                  19239 non-null object
yardlineSide              18985 non-null object
yardlineNumber            19239 non-null int64
offenseFormation          19098 non-null object
personnelO                19210 non-null object
defendersInTheBox         19177 non-null float64
numberOfPassRushers       18606 non-null float64
personnelD                19210 non-null object
typeDropback              18600 non-null object
preSnapVisitorScore       18600 non-null float64
preSnapHomeScore          18600 non-null float64
gameClock                 18600 non-null object
absoluteYardlineNumber    18600 non-null float64
penaltyCodes              1206 non-null object
penaltyJerseyNumbers      1206 non-null object
passResult                19237 non-null object
offensePlayResult         19239 non-null int64
playResult                19239 non-null int64
epa                       19239 non-null float64
isDefensivePI             19239 non-null bool
dtypes: bool(1), float64(6), int64(8), object(12)
memory usage: 3.8+ MB

In [37]:
plays_data

,gameId,playId,playDescription,quarter,down,yardsToGo,possessionTeam,playType,yardlineSide,yardlineNumber,...,preSnapHomeScore,gameClock,absoluteYardlineNumber,penaltyCodes,penaltyJerseyNumbers,passResult,offensePlayResult,playResult,epa,isDefensivePI
0,2018090600,75,(15:00) M.Ryan pass short right to J.Jones pus...,1,1,15,ATL,play_type_pass,ATL,20,...,0.0,15:00:00,90.0,NaN,NaN,C,10,10,0.261827,False
1,2018090600,146,(13:10) M.Ryan pass incomplete short right to ...,1,1,10,ATL,play_type_pass,PHI,39,...,0.0,13:10:00,49.0,NaN,NaN,I,0,0,-0.372360,False
2,2018090600,168,(13:05) (Shotgun) M.Ryan pass incomplete short...,1,2,10,ATL,play_type_pass,PHI,39,...,0.0,13:05:00,49.0,NaN,NaN,I,0,0,-0.702779,False
3,2018090600,190,(13:01) (Shotgun) M.Ryan pass deep left to J.J...,1,3,10,ATL,play_type_pass,PHI,39,...,0.0,13:01:00,49.0,NaN,NaN,C,33,33,3.047530,False
4,2018090600,256,(10:59) (Shotgun) M.Ryan pass incomplete short...,1,3,1,ATL,play_type_pass,PHI,1,...,0.0,10:59:00,11.0,NaN,NaN,I,0,0,-0.842272,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19234,2018122200,2300,(7:53) J.Johnson pass incomplete short left [K...,3,2,5,WAS,play_type_unknown,WAS,31,...,NaN,NaN,NaN,DH,TEN 24,I,0,5,0.848703,False
19235,2018122200,3177,(6:53) (Shotgun) B.Gabbert pass incomplete sho...,4,3,7,TEN,play_type_unknown,WAS,37,...,NaN,NaN,NaN,DH,WAS 31,I,0,5,1.227695,False
19236,2018122201,566,(5:32) (Shotgun) P.Rivers pass deep right to K...,1,3,4,LAC,play_type_unknown,LAC,49,...,NaN,NaN,NaN,OPI,LAC 13,C,27,-10,-0.720168,False
19237,2018122201,1719,(1:08) P.Rivers pass incomplete deep middle to...,2,3,1,LAC,play_type_unknown,LAC,48,...,NaN,NaN,NaN,DPI,BAL 23,I,0,15,1.336078,True
19238,2018122201,2649,(7:16) (Shotgun) L.Jackson pass incomplete sho...,3,1,10,BAL,play_type_unknown,LAC,49,...,NaN,NaN,NaN,DPI,LAC 43,I,0,9,0.550256,True

In [55]:
plays_data.passResult.value_counts()

C     11370
I      6135
S      1308
IN      420
R         4
Name: passResult, dtype: int64

In [39]:
plays_data.columns

Index(['gameId', 'playId', 'playDescription', 'quarter', 'down', 'yardsToGo',
       'possessionTeam', 'playType', 'yardlineSide', 'yardlineNumber',
       'offenseFormation', 'personnelO', 'defendersInTheBox',
       'numberOfPassRushers', 'personnelD', 'typeDropback',
       'preSnapVisitorScore', 'preSnapHomeScore', 'gameClock',
       'absoluteYardlineNumber', 'penaltyCodes', 'penaltyJerseyNumbers',
       'passResult', 'offensePlayResult', 'playResult', 'epa',
       'isDefensivePI'],
      dtype='object')

## Important features to look at in the data

- gameId / playId - tie into the 2 previous dataframes

- playdescription - seems less useful but will be good to keep to have an idea of the play in a much more readable way

- quarter/down/yards to go - all important when trying to analyze the plays. longer yardstogo, on 2nd/3rd/4th down will likely result in less successful but deeper passes and vice versa for shorter yardstogo.

- playtype are all passing plays. Some will be sacks, some passes and unknown will encompass the rest, likely interceptions/flags that result in yards, all important as they are the results. May not be included when trying to analyze results in a model. Will be very correlated to whether or not a play is successful

- yardslineside / yardlinenumber - where they are starting the play. very important. bigger fields usually lead to more successful chances and more points

- offenseFormation / personnelO - the way the offense is set up and how many of each position they have. Will need to clean this up as there are some weirdly set up formations that sometimes write 0 of a position, as well as have defensvive formations in there.

- defendersInTheBox / numberofPassRushers - overview of the type of pressure the other team is putting on the offense.

- personnelD - same as offensive personnel for the other side. again needs to be cleaned so it doesnt include defensive players

- typeDropback - the type of passing play. Very important as scrambles are often a biproduct of aggressive defense and can result in big plays or busts, more rare to be inbetween.

- 'preSnapVisitorScore', 'preSnapHomeScore', 'gameClock' - overview of the current state of the game. similar to down and distance could be very valuable as teams further behind will look for bigger plays while teams ahead may be safer

- absoluteyardlinenumber - can be covered using the yardline numbers and side instead. but could be useful to see how deep into the endzone some plays end up

- penaltyCodes - due to the excessiveness of the distinct types of penalties will likely turn out to be much less useful than the yardage result

- penaltyJerseyNumbers - who commited the penalty

- pass result - catch, incomplete, sack, interception (r is likely run but that is not relevant to us)

- offensive play result / play result - these are the be all end all of this. how many yards does each play get. The big distinction is that offensive play result does not include penalties, just the actual catch/drop. where as play result is the final action including penalties. Will be checked and if they are not equal it means there was a penalty and if they are then there was no penalty or the penalty was declined.

- epa - estimated points added

- is defensive past interference - important penalty for passing plays

# Looking at Week 1 to see what are some basics i can begin to pull out of the data

In [2]:
week_1 = pd.read_csv('week1.csv')

In [4]:
week_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 986022 entries, 0 to 986021
Data columns (total 19 columns):
time             986022 non-null object
x                986022 non-null float64
y                986022 non-null float64
s                986022 non-null float64
a                986022 non-null float64
dis              986022 non-null float64
o                919109 non-null float64
dir              919109 non-null float64
event            986022 non-null object
nflId            919109 non-null float64
displayName      986022 non-null object
jerseyNumber     919109 non-null float64
position         919109 non-null object
frameId          986022 non-null int64
team             986022 non-null object
gameId           986022 non-null int64
playId           986022 non-null int64
playDirection    986022 non-null object
route            273314 non-null object
dtypes: float64(9), int64(3), object(7)
memory usage: 142.9+ MB

In [5]:
week_1

,time,x,y,s,a,dis,o,dir,event,nflId,displayName,jerseyNumber,position,frameId,team,gameId,playId,playDirection,route
0,2018-09-07T01:07:14.599Z,91.73,26.67,0.00,0.01,0.02,289.57,240.93,None,310.0,Matt Ryan,2.0,QB,1,away,2018090600,75,left,NaN
1,2018-09-07T01:07:14.599Z,88.89,36.47,0.01,0.01,0.01,105.63,66.66,None,79848.0,Malcolm Jenkins,27.0,SS,1,home,2018090600,75,left,NaN
2,2018-09-07T01:07:14.599Z,91.35,44.16,0.02,0.03,0.01,290.45,16.86,None,2495454.0,Julio Jones,11.0,WR,1,away,2018090600,75,left,HITCH
3,2018-09-07T01:07:14.599Z,86.31,22.01,0.09,0.42,0.01,70.12,168.91,None,2495613.0,Corey Graham,24.0,FS,1,home,2018090600,75,left,NaN
4,2018-09-07T01:07:14.599Z,90.78,36.15,0.00,0.00,0.00,257.61,193.97,None,2533040.0,Mohamed Sanu,12.0,WR,1,away,2018090600,75,left,HITCH
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
986017,2018-09-11T05:29:39.900Z,33.68,43.14,1.96,3.79,0.22,281.35,309.70,None,2556277.0,Marqui Christian,41.0,SS,65,away,2018091001,4192,left,NaN
986018,2018-09-11T05:29:39.900Z,36.02,40.21,0.81,1.52,0.09,308.07,234.06,None,2556593.0,Cory Littleton,58.0,ILB,65,away,2018091001,4192,left,NaN
986019,2018-09-11T05:29:39.900Z,33.02,43.81,2.63,4.57,0.27,183.83,314.39,None,2556885.0,Jalen Richard,30.0,RB,65,home,2018091001,4192,left,SCREEN
986020,2018-09-11T05:29:39.900Z,34.13,40.86,0.15,0.72,0.02,6.17,267.87,None,2558183.0,John Johnson,43.0,SS,65,away,2018091001,4192,left,NaN
986021,2018-09-11T05:29:39.900Z,33.29,43.92,1.81,4.24,0.20,NaN,NaN,None,NaN,Football,NaN,NaN,65,football,2018091001,4192,left,NaN

## Understanding the data

- time - time stamp of the play, time, y-m-d, h-m-s
- x - players x position on the field, goes from 0-120
- y - players y position on the field, goes from 0 to 53.3
- s - spead in yards per second
- a - acceleration in yards per second squared
- dis - distance traveled from the previous time point
- o - player orientation - in degrees 0-360
- dir - angle of players motion in degrees 0-360
- event - tagged play details (for moment of ball snap, pass release, pass catch etc
- nflId - player identification (ties in to player data)
- display name - player name
- jersey number - player number
- position - player position group
- team - home or away of corresponding player
- frameid - frame identifier for each play
- gameid - correlates to the games dataframe
- playid - game identifier
- play direction - left or right
- route - route ran by a specific player